services:
  - type: web
    name: multiuser-music-website
    env: node
    plan: free
    buildCommand: "npm install --prefix frontend/backend && npm install --prefix frontend && npm run build --prefix frontend"
    startCommand: "npm start --prefix frontend/backend"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
